name: on_screen_keyboard
description: A simple package for displaying on screen keyboards on a devices like kiosks and ATMs.
  The library is written in Dart and has no native code dependency.
version: 1.2.0
homepage: https://github.com/BMEC/on_screen_keyboard

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
